# Live symlinks: checkout edits are visible without rebuilding Nix.
{ ... }:
{
  home-manager.users.ahmed = { config, ... }:
    let
      repo = "${config.home.homeDirectory}/github/awesome-dots";
      link = relative: config.lib.file.mkOutOfStoreSymlink "${repo}/${relative}";
    in {
      home.file = {
        ".pi/agent/settings.json".source = link "pi/settings.json";
        ".pi/agent/keybindings.json".source = link "pi/keybindings.json";
        ".pi/agent/extensions".source = link "pi/extensions";
        ".pi/agent/skills".source = link "pi/skills";
        ".pi/agent/prompts".source = link "pi/prompts";
        ".pi/agent/themes".source = link "pi/themes";
        ".zshrc".source = link ".zshrc";
        ".aliases.zsh".source = link ".aliases.zsh";
        ".p10k.zsh".source = link ".p10k.zsh";
        ".gitconfig".source = link "gitconfig";
      };
      xdg.configFile = {
        "ghostty/config".source = link "ghostty/config";
        "hypr".source = link "hypr";
        "waybar".source = link "waybar";
        "wofi".source = link "wofi";
        # init.lua remains generated by Home Manager to load Nix plugin paths.
        "nvim/lua".source = link "nvim/lua";
        "nvim/options.lua".source = link "nvim/options.lua";
        "nvim/keymap.lua".source = link "nvim/keymap.lua";
        "nvim/plugins".source = link "nvim/plugins";
      };
    };
}
